export function useProducts() {
    const productsList = ref([
        {
            id: 1,
            title: 'Black and white sport cap',
            image: '/images/products/product-1.png',
            price: 18.15,
            score: 2,
            sizes: [45, 46, 47, 49],
            colors: [],
        },
        {
            id: 2,
            title: 'Metal bridge sunglasses',
            image: '/images/products/product-2.png',
            price: 89.95,
            score: NaN,
            sizes: [],
            colors: [],
        },
        {
            id: 3,
            title: 'Green baby romper',
            image: '/images/products/product-3.png',
            price: 20.40,
            score: 4,
            sizes: [26, 27, 28],
            colors: ['#17696A', '#874E19', '#C0DDED'],
        },
        {
            id: 4,
            title: 'Mid-rise slim cropped fit jeans',
            image: '/images/products/product-4.png',
            price: 40.00,
            score: NaN,
            sizes: [36, 37, 38],
            colors: ['#17696A', '#874E19'],
        },
        {
            id: 5,
            title: 'Red dangle earrings',
            image: '/images/products/product-5.png',
            price: 29.95,
            score: 5,
            sizes: [36, 37, 38],
            colors: [],
        },
        {
            id: 6,
            title: 'Baby shoes with laces',
            image: '/images/products/product-6.png',
            price: 30.60,
            score: NaN,
            sizes: [36, 37, 38],
            colors: ['#874E19', '#C0DDED'],
        },
        {
            id: 7,
            title: 'Shirt with insertion lace trims',
            image: '/images/products/product-7.png',
            price: 49.95,
            score: 5,
            sizes: [46, 47, 48, 49, 50],
            colors: ['#874E19', '#C0DDED'],
        },
        {
            id: 8,
            title: 'Chrono watch with blue leather belt',
            image: '/images/products/product-8.png',
            price: 120.60,
            score: 4,
            sizes: [],
            colors: [],
        },
        {
            id: 9,
            title: 'Check coat with colour contrast',
            image: '/images/products/product-9.png',
            price: 183.45,
            score: NaN,
            sizes: [46, 47, 48, 49, 50],
            colors: ['#874E19', '#C0DDED'],
        },
        {
            id: 10,
            title: 'Leather crossbody bag with gold hardware',
            image: '/images/products/product-10.png',
            price: 179.00,
            sale: 50,
            score: 4,
            sizes: [],
            colors: ['#874E19', '#C0DDED'],
        },
        {
            id: 11,
            title: 'Skinny push-up jeans',
            image: '/images/products/product-11.png',
            price: 80.00,
            sale: 50,
            score: NaN,
            sizes: [46, 47, 48, 49, 50],
            colors: ['#874E19', '#C0DDED'],
        },
        {
            id: 12,
            title: 'Wide heel suede ankle boots',
            image: '/images/products/product-12.png',
            price: 148.95,
            sale: 20,
            score: NaN,
            sizes: [36, 37, 38, 39, 40],
            colors: ['#000000', '#874E19', '#C0DDED'],
        },
    ]);

    return {
        productsList,
    };
}